# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

# Мод
mod_id=bulletin_board
mod_name=Bulletin Board Mod
mod_license=MIT
mod_version=1.3
mod_group_id=com.unnameduser
mod_authors=UnnamedUser
mod_description=A mod for bulletin boards with living world features

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
